// Logical database backup for the Supabase Postgres instance.
// Dumps every table to a timestamped folder as both JSON (data) and SQL
// (schema + INSERT statements) so the current state can be fully restored.
// Works over the transaction pooler — no pg_dump required.
//
//   node scripts/backup-db.js
//
// Output: backups/<YYYY-MM-DD_HHmmss>/{data.json, restore.sql, manifest.json}

const { Client } = require('pg');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: '.env.local' });

// Dumped in dependency order so restore.sql can be replayed top-to-bottom.
const TABLES = [
  'classes',
  'teachers',
  'subjects',
  'students',
  'assessments',
  'subtopics',
  'ratings',
];

function stamp() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}_${p(
    d.getHours()
  )}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

function sqlLiteral(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (v instanceof Date) return `'${v.toISOString()}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function run() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();

  const dir = path.join(__dirname, '..', 'backups', stamp());
  fs.mkdirSync(dir, { recursive: true });
  console.log('Backing up to', dir);

  const data = {};
  const manifest = { createdAt: new Date().toISOString(), tables: {} };
  const sqlParts = [
    '-- Logical backup generated by scripts/backup-db.js',
    `-- Created: ${new Date().toISOString()}`,
    'BEGIN;',
    '',
  ];

  for (const table of TABLES) {
    let rows = [];
    try {
      const res = await client.query(`SELECT * FROM ${table} ORDER BY id`);
      rows = res.rows;
    } catch (err) {
      // Table may not exist yet (e.g. fresh schema variant); record and skip.
      console.warn(`  ${table}: skipped (${err.message})`);
      manifest.tables[table] = { rows: 0, skipped: true, error: err.message };
      continue;
    }

    data[table] = rows;
    manifest.tables[table] = { rows: rows.length };
    console.log(`  ${table}: ${rows.length} row(s)`);

    if (rows.length) {
      const cols = Object.keys(rows[0]);
      sqlParts.push(`-- ${table} (${rows.length} rows)`);
      for (const row of rows) {
        const vals = cols.map((c) => sqlLiteral(row[c])).join(', ');
        sqlParts.push(
          `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${vals});`
        );
      }
      // Keep SERIAL sequences ahead of the restored max id.
      sqlParts.push(
        `SELECT setval(pg_get_serial_sequence('${table}', 'id'), (SELECT COALESCE(MAX(id), 1) FROM ${table}));`
      );
      sqlParts.push('');
    }
  }

  sqlParts.push('COMMIT;');

  fs.writeFileSync(
    path.join(dir, 'data.json'),
    JSON.stringify(data, null, 2),
    'utf8'
  );
  fs.writeFileSync(path.join(dir, 'restore.sql'), sqlParts.join('\n'), 'utf8');
  fs.writeFileSync(
    path.join(dir, 'manifest.json'),
    JSON.stringify(manifest, null, 2),
    'utf8'
  );

  await client.end();
  console.log('\n✅ Backup complete.');
  console.log(JSON.stringify(manifest.tables, null, 2));
}

run().catch((err) => {
  console.error('\n❌ Backup failed:', err.message);
  process.exit(1);
});
